
# Model arguments
model_name_or_path: /home/wxt/huatong/huggingface/hub/llama2_sft_mirror 
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  trl-internal-testing/hh-rlhf-trl-style: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
# hub_model_id: zephyr-7b-dpo-full
learning_rate: 1e-6
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1024
num_train_epochs: 1
optim: adamw_torch
output_dir: /home/wxt/huatong/huggingface/hub/llama2_dpo_handbook
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
push_to_hub: false
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
